services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pawesome
      POSTGRES_PASSWORD: pawesome
      POSTGRES_DB: pawesome
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pawesome" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data: