services:
  pawesome:
    container_name: pawesome_app
    image: pawesome
    build:
      context: .
      dockerfile: Pawesome/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pawesome.rule=Host(`pawesome.club`)"
      - "traefik.http.routers.pawesome.entrypoints=websecure"
      - "traefik.http.routers.pawesome.tls.certresolver=letsencrypt"
      - "traefik.http.services.pawesome.loadbalancer.server.port=8080"
    
      - "traefik.http.routers.pawesome-http.rule=Host(`pawesome.club`)"
      - "traefik.http.routers.pawesome-http.entrypoints=web"
      - "traefik.http.routers.pawesome-http.middlewares=https-redirect"
    
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
    networks:
      - pawesome-network
      - traefik-proxy
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: pawesome_db
    image: postgres:latest
    environment:
      POSTGRES_USER: pawesome
      POSTGRES_PASSWORD: pawesome
      POSTGRES_DB: pawesome
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pawesome-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pawesome" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data:

networks:
  pawesome-network:
    driver: bridge
  traefik-proxy:
    external: true
