[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[tls]
  [[tls.certificates]]
    certFile = "/etc/traefik/certs/haproxy-wildcard.crt"
    keyFile = "/etc/traefik/certs/haproxy-wildcard.key"

[providers.docker]
  exposedByDefault = false

[api]
  dashboard = false
  insecure = false