FROM mcr.microsoft.com/dotnet/sdk:9.0 AS development
WORKDIR /app
EXPOSE 8080

COPY ["Pawesome/Pawesome.csproj", "Pawesome/"]
RUN dotnet restore "Pawesome/Pawesome.csproj"
COPY . .

WORKDIR "/app/Pawesome"
# Changed to only use HTTP
ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]